<?php

namespace AppBundle\Repository;

/**
 * PrestationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrestationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllPerMonth($start, $end, $user)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT p FROM AppBundle:Prestation p WHERE p.prestationDate >= :startDate AND p.prestationDate <= :endDate AND p.user = :user"
            )
            ->setParameter(':startDate', $start)
            ->setParameter(':endDate', $end)
            ->setParameter(':user', $user)
            ->getResult();
    }
}
