# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        manapresta:
            entity:
                class: AppBundle\Entity\User
                property: email
                # if you're using multiple entity managers
                # manager_name: customer

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: manapresta
            form_login:
                login_path: homepage
                check_path: homepage
                default_target_path: member

            logout:
                invalidate_session: true
                path: /logout
                target: /
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
        - { path: ^/member, roles: ROLE_USER }
        - { path: ^/employer, roles: ROLE_USER }
        - { path: ^/prestation, roles: ROLE_USER }
        - { path: /, roles: IS_AUTHENTICATED_ANONYMOUSLY }